config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :booths

  mount API => "/api"

  resources :ava_beacon do
    collection do
      get 'tracking_realtime'
      get 'heatmap_realtime'
      get 'heatmap_term'
    end
  end

end

app/models/beacon.rb
class Beacon
  include Mongoid::Document
  field :lon, type: Float
  field :lat, type: Float
  field :radius, type: Float

  def same_location?(arg)
    self.lon === arg.lon && self.lat === arg.lat
  end
end

app/models/beacon_sensing_data.rb
class BeaconSensingData
  include Mongoid::Document
  field :t, type: DateTime
  field :mobile_t, type: DateTime
  field :mobile_uuid, type: String
  field :point_lon, type: Float
  field :point_lat, type: Float
  embeds_many :beacons
end

app/models/booth.rb
class Booth
  include Mongoid::Document
  field :title, type: String
  field :no, type: String
end

app/models/sensor_log.rb
class SensorLog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ava_beacon_controller.rb
class AvaBeaconController < ApplicationController
  layout 'beacon'

  EXPAND = 'expand'

  # for login
#  before_filter :authenticate_user!


  def tracking_realtime
    @expand = EXPAND
  end

  def heatmap_realtime
    @expand = EXPAND
  end

  def heatmap_term
    @expand = nil
  end

end

app/controllers/booths_controller.rb
class BoothsController < ApplicationController
  before_action :set_booth, only: [:show, :edit, :update, :destroy]

  # GET /booths
  # GET /booths.json
  def index
    @booths = Booth.all
  end

  # GET /booths/1
  # GET /booths/1.json
  def show
  end

  # GET /booths/new
  def new
    @booth = Booth.new
  end

  # GET /booths/1/edit
  def edit
  end

  # POST /booths
  # POST /booths.json
  def create
    @booth = Booth.new(booth_params)

    respond_to do |format|
      if @booth.save
        format.html { redirect_to @booth, notice: 'Booth was successfully created.' }
        format.json { render :show, status: :created, location: @booth }
      else
        format.html { render :new }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booths/1
  # PATCH/PUT /booths/1.json
  def update
    respond_to do |format|
      if @booth.update(booth_params)
        format.html { redirect_to @booth, notice: 'Booth was successfully updated.' }
        format.json { render :show, status: :ok, location: @booth }
      else
        format.html { render :edit }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booths/1
  # DELETE /booths/1.json
  def destroy
    @booth.destroy
    respond_to do |format|
      format.html { redirect_to booths_url, notice: 'Booth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booth
      @booth = Booth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booth_params
      params.require(:booth).permit(:title, :no)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  MOBILE_UUID_1 = '8001b15fd49640e5b01cbd9443a36f05' #iPod touch 青
  #MOBILE_UUID_2 = 'a552fb7609494734b781938b39aea1df' #iPod touch 黄
  #MOBILE_UUID_3 = '63626feb547e484682636c601a09bb73' #iPod touch ピンク
  MOBILE_UUID_3 = 'a552fb7609494734b781938b39aea1df' #iPod touch 黄
  MOBILE_UUID_2 = '63626feb547e484682636c601a09bb73' #iPod touch ピンク
  MOBILE_UUID_4 = '3810f6bbd3a34c70ba3da0c80b05389f' #iPhone5
end

app/helpers/booths_helper.rb
module BoothsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ava_beacon/_beacon_js.html.erb
var diagramExpand;

<% if @expand %>
diagramExpand = '<%= @expand %>';
<% else %>
diagramExpand = null;
<% end %>

/*var w = 750;
var h = 500;*/
var w = 660;
var h = 440;
/*var h = 750;*/

var beacon_w = 14;
var beacon_h = 14;

var diagram = d3.select("#diagram");

var initBeacon = function() {

  var drawBeacons = function(beacons) {

console.log('data count ' + beacons.length);

    diagram.selectAll("*").remove();

    diagram.selectAll("rect")
    .data(beacons)
    .enter()
    .append("rect")
    .attr("x", function(d) {
      return (d['x'] - beacon_w/2);
    })
    .attr("y", function(d) {
      return (d['y'] - beacon_h/2);
    })
    .attr("width", beacon_w)
    .attr("height", beacon_h)
    .attr("fill", "rgba(0, 255, 0, 0.5)");
  };

  console.log('beacon_js >> diagramExpand :: ' + diagramExpand);


  $.ajax({
    //url :"http://54.64.20.148/api/beacons/",
    url :"/api/beacons/",
    dataType : "jsonp",
    data : {
      expand : diagramExpand,
    }
  }).done(function(data){
console.log("done");
    drawBeacons(data);
  }).fail(function(data){
console.log("error");
    alert("error");
  }).always(function(data){
    // do nothing
console.log("result");
  });

};

initBeacon(diagramExpand);

app/views/ava_beacon/_mobile_uuids.html.erb
<div id="mobile-uuids">
  <label id="mu01" title="iPod touch 青">
    <%= image_tag 'phone1_on.png', :id => 'phone1_on', :class => 'phone1' %>
    <%= image_tag 'phone1_off.png', :id => 'phone1_off', :class => 'phone1' %>
    <input type="checkbox" name="mobile-uuid" id="mobile-uuid-1" value="<%= ApplicationHelper::MOBILE_UUID_1 %>"> <!--iPod touch 青-->
  </label>
  <label id="mu02" title="iPod touch ピンク">
    <%= image_tag 'phone2_on.png', :id => 'phone2_on', :class => 'phone2' %>
    <%= image_tag 'phone2_off.png', :id => 'phone2_off', :class => 'phone2' %>
    <input type="checkbox" name="mobile-uuid" id="mobile-uuid-2" value="<%= ApplicationHelper::MOBILE_UUID_2 %>"> <!--iPod touch ピンク-->
  </label>
  <label id="mu03" title="iPod touch 黄">
    <%= image_tag 'phone3_on.png', :id => 'phone3_on', :class => 'phone3' %>
    <%= image_tag 'phone3_off.png', :id => 'phone3_off', :class => 'phone3' %>
    <input type="checkbox" name="mobile-uuid" id="mobile-uuid-3" value="<%= ApplicationHelper::MOBILE_UUID_3 %>"> <!--iPod touch 黄-->
  </label>
  <label id="mu04" title="iPhone5">
    <%= image_tag 'phone4_on.png', :id => 'phone4_on', :class => 'phone4' %>
    <%= image_tag 'phone4_off.png', :id => 'phone4_off', :class => 'phone4' %>
    <input type="checkbox" name="mobile-uuid" id="mobile-uuid-4" value="<%= ApplicationHelper::MOBILE_UUID_4 %>"> <!--iPhone5 -->
  </label>
</div><!-- /#mobile_uuids -->

app/views/ava_beacon/_mobile_uuids_js.html.erb
$('#phone1_on').hide();
$('#phone1_off').show();
$('#phone2_on').hide();
$('#phone2_off').show();
$('#phone3_on').hide();
$('#phone3_off').show();
$('#phone4_on').hide();
$('#phone4_off').show();

if ($('#mobile-uuid-1:checked').val()) $('.phone1').toggle();
if ($('#mobile-uuid-2:checked').val()) $('.phone2').toggle(); 
if ($('#mobile-uuid-3:checked').val()) $('.phone3').toggle(); 
if ($('#mobile-uuid-4:checked').val()) $('.phone4').toggle(); 

$('.phone1').click(function(){ $('.phone1').toggle(); });
$('.phone2').click(function(){ $('.phone2').toggle(); });
$('.phone3').click(function(){ $('.phone3').toggle(); });
$('.phone4').click(function(){ $('.phone4').toggle(); });

app/views/ava_beacon/_realtime_core_js.html.erb
var getMobileLocations;
var stopFlag;
var startDate;

// playボタンを活性
$('#slide-play').show();
$('#slide-pause').hide();

$('#slide-play').click(function() {
    var mobileUuids = [];
    $('[name="mobile-uuid"]:checked').each(function(){
      mobileUuids.push($(this).val());
    });

    if (mobileUuids.length == 0) {
      alert('対象機器を選択してください');
      return;
    }

    stopFlag = false;

    // playボタンを非活性
    $(this).hide();
    $('#slide-pause').show();

    // 各種ボタンも非活性
    guardButtons(true);

    var loopCnt = 0;
    if (!startDate) startDate = formatDate(new Date(),'YYYY-MM-DD hh:mm:ss');
    //console.log(startDate);

    getMobileLocations = setInterval(function() {
      //console.log('loopCnt = ' + loopCnt);

      //console.log('realtime_core_js >> diagramExpand :: ' + diagramExpand);

      $.ajax({
        //url :"http://localhost:3000/api/mobile_locations/",
        url :"http://54.64.20.148/api/mobile_locations/",
        dataType : "jsonp",
        data : {
          //start_dt : '2014-09-29 14:00:00',
          //start_dt : '2014-09-24 14:00:00',
          start_dt : startDate,
          mobile_uuids : mobileUuids,
          expand : diagramExpand,
        }
        }).done(function(data){
          if(!stopFlag) {
            setResult(data);
          }
        }).fail(function(data){
          console.log('error');
          // alert("error");
        }).always(function(data){
          // do nothing
        });

      loopCnt = loopCnt + 1;

/*
      // 弱気に、300,000回実行(5分間)をMAXとする 
      if (loopCnt == 300000) {
        alert('念のために、5分間でループ終了します');
        clearInterval(getMobileLocations);
      }
*/
    }, 2000);
});

$('#slide-pause').click(function() {
    // ループ処理を停止
    stopFlag = true;
    clearInterval(getMobileLocations);
    // startDate = null; // startDateは初期化しない

    // playボタンを活性
    $(this).hide();
    $('#slide-play').show();

    // 各種ボタン非活性
    guardButtons(false);
});

/*
$('#slide-stop').click(function() {
    // ループ処理を停止
    stopFlag = true;
    clearInterval(getMobileLocations);
    startDate = null;

    // heatmapを初期化
    clearDiagram();
    // playボタンを活性
    $('#slide-play').attr('disabled', false);
    //toggleMobileUuidsCB(false);
});
*/

app/views/ava_beacon/_slide_buttons.html.erb
<div class="slide-buttons">
  <label id="slide-play" title="再生">
    <i class="fa fa-play"></i>
  </label>
  <label id="slide-pause" title="一時停止">
    <i class="fa fa-pause"></i>
  </label>
<!--
  <label id="slide-stop">
    <i class="fa fa-stop"></i>
  </label>
-->
</div> 

app/views/ava_beacon/_zoom_buttons.html.erb
<div id="zoom-buttons" class="text-right">
  <div id="zoom-guard" class="guard">
  </div>
  <label id="diagram-zoom-in" title="拡大図">
    <%= image_tag 'zoom_on.png' %>
  </label>
  <label id="diagram-zoom-in-off" title="拡大図">
    <%= image_tag 'zoom_off.png' %>
  </label>
  <label id="diagram-zoom-out" title="全体図">
    <%= image_tag 'reduct_on.png' %>
  </label>
  <label id="diagram-zoom-out-off" title="全体図">
    <%= image_tag 'reduct_off.png' %>
  </label>
</div><!-- /.zoom-bottons -->

app/views/ava_beacon/_zoom_js.html.erb
var dispZoomButtons = function() {
  if (diagramExpand === 'expand') {
    $('#diagram-zoom-in').hide();
    $('#diagram-zoom-in-off').show();
    $('#diagram-zoom-out').show();
    $('#diagram-zoom-out-off').hide();

    $('#diagram-wrapper').removeClass('zoom-out');
    $('#diagram-wrapper').addClass('zoom-in');
  } else {
    $('#diagram-zoom-in').show();
    $('#diagram-zoom-in-off').hide();
    $('#diagram-zoom-out').hide();
    $('#diagram-zoom-out-off').show();

    $('#diagram-wrapper').removeClass('zoom-in');
    $('#diagram-wrapper').addClass('zoom-out');
  };
}

dispZoomButtons();


$('#diagram-zoom-in').click(function() {
  if (!confirm('拡大図に切り替えますか？')) return;

  diagramExpand = 'expand';

  initBeacon();
  dispZoomButtons();
  clearDiagram();
});

$('#diagram-zoom-out').click(function() {
  if (!confirm('全体図に切り替えますか？')) return;

  diagramExpand = null;

  initBeacon();
  dispZoomButtons();
  clearDiagram();
});

app/views/ava_beacon/heatmap_realtime.html.erb
<% content_for :page_title do %>
  <%= image_tag 'heatmap_real_b.png' %>
<% end %>

<% content_for :cond do %>
  <div class="col-md-4">
    <%= render 'mobile_uuids' %>
  </div>
  <div class="col-md-4">
    <!--2-->
  </div>
  <div class="col-md-4">
    <!--3-->
  </div>
<% end %>

<% content_for :slide_ctrl do %>
  <%= render 'slide_buttons' %>
<% end %>

<!--
<div class="page-header">
  <h1>テスト環境 写真</h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">

    <a href="<%= image_url('IMG_0622.JPG') %>" class="gallery" rel="beacon" title="テスト環境 写真">
      <%= image_tag('IMG_0622.JPG', :height => 100) %>
    </a> 
    <a href="<%= image_url('IMG_0623.JPG') %>" class="gallery" rel="beacon" rel="pict" title="テスト環境 写真">
      <%= image_tag('IMG_0623.JPG', :height => 100) %>
    </a> 
    <a href="<%= image_url('IMG_0624.JPG') %>" class="gallery" rel="beacon" rel="pict" title="テスト環境 写真">
      <%= image_tag('IMG_0624.JPG', :height => 100) %>
    </a> 
    <a href="<%= image_url('IMG_0625.JPG') %>" class="gallery" rel="beacon" title="テスト環境 写真">
      <%= image_tag('IMG_0625.JPG', :height => 100) %>
    </a> 
    <a href="<%= image_url('IMG_0626.JPG') %>" class="gallery" rel="beacon" title="テスト環境 写真">
      <%= image_tag('IMG_0626.JPG', :height => 100) %>
    </a> 
    <a href="<%= image_url('IMG_0627.JPG') %>" class="gallery" rel="beacon" title="テスト環境 写真">
      <%= image_tag('IMG_0627.JPG', :height => 100) %>
    </a> 
    <a href="<%= image_url('IMG_0628.JPG') %>" class="gallery" rel="beacon" title="テスト環境 写真">
      <%= image_tag('IMG_0628.JPG', :height => 100) %>
    </a> 
    <a href="<%= image_url('IMG_0629.JPG') %>" class="gallery" rel="beacon"  title="テスト環境 写真">
      <%= image_tag('IMG_0629.JPG', :height => 100) %>
    </a> 
  </div>
</div>
-->

<script>
// ビーコン表示 >>
<%= render 'beacon_js' %>
// << ビーコン表示

// モバイル端末ボタン制御 >>
<%= render 'mobile_uuids_js' %>
// << モバイル端末ボタン制御

// ズームボタン制御 >>
<%= render 'zoom_js' %>
// << ズームボタン制御

var heatmapInstance = h337.create({
                          container: document.querySelector('#diagram-wrapper'),
                          radius: 20,
                          });
//heatmapInstance.setDataMax(75).setDataMin(0);
//setResult([{x:100, y:100, value:1}]);

function clearDiagram() {
    heatmapInstance.setData({data:[]});
};

function setResult(json) {
  console.log('setResult start');
  console.log('data count = ' + json.length);

  var data = {
      max: 10,
      min: 0,
      data: json
  };
  heatmapInstance.setData(data);

  console.log('setResult end');
};


// realtime表示のコア処理 >>
<%= render 'realtime_core_js' %>
// << realtime表示のコア処理

// テスト環境写真
//$('a.gallery').colorbox({width: 700});

</script>

app/views/ava_beacon/heatmap_term.html.erb
<% content_for :page_title do %>
  <%= image_tag 'heatmap_data_b.png' %>
<% end %>

<% content_for :cond do %>
  <div class="col-sm-4">
    <%= render 'mobile_uuids' %>
  </div>
  <div class="col-sm-3 ctl-align-top">
    <div class="input-group">
      <input id="term-date" class="form-control">
      <span class="input-group-addon">
        <i class="fa fa-calendar"></i>
      </span>
    </div>
  </div>
  <div class="col-sm-3 ctl-align-top">
    <select id="target-hour" class="form-control">
      <option value="00"> 0:00 〜 1:00
      <option value="01"> 1:00 〜 2:00
      <option value="02"> 2:00 〜 3:00
      <option value="03"> 3:00 〜 4:00
      <option value="04"> 4:00 〜 5:00
      <option value="05"> 5:00 〜 6:00
      <option value="06"> 6:00 〜 7:00
      <option value="07"> 7:00 〜 8:00
      <option value="08"> 8:00 〜 9:00
      <option value="09"> 9:00 〜 10:00
      <option value="10"> 10:00 ～ 11:00
      <option value="11"> 11:00 ～ 12:00
      <option value="12"> 12:00 ～ 13:00
      <option value="13"> 13:00 ～ 14:00
      <option value="14"> 14:00 ～ 15:00
      <option value="15"> 15:00 ～ 16:00
      <option value="16"> 16:00 ～ 17:00
      <option value="17"> 17:00 ～ 18:00
      <option value="18"> 18:00 ～ 19:00
      <option value="19"> 19:00 ～ 20:00
      <option value="20"> 20:00 ～ 21:00
      <option value="21"> 21:00 ～ 22:00
      <option value="22"> 22:00 ～ 23:00
      <option value="23"> 23:00 ～ 24:00
    </select>
  </div>
  <div class="col-sm-2 ctl-align-top">
    <button type="button" id="loading-btn" data-loading-text="Loading..." class="btn btn-primary btn-block">Loading</button>
  </div>
<% end %>

<% content_for :slide_ctrl do %>
  <div id="heatmap_term_slide_ctrl">
    <%= render 'slide_buttons' %>
    <input id="hide-slider" data-slider-id='time-slider' type="text" data-slider-min="0" data-slider-max="60" data-slider-step="5" data-slider-value="0"/>

    <!--<span id="slider-val-lbl"><span id="slider-val">0</span> 分</span>-->

    <div class="slide-buttons">
      <label id="slide-play-repeat" title="リピート再生">
        <i id="repeat_on" class="fa fa-spin fa-refresh"></i>
        <i id="repeat_off" class="fa fa-refresh"></i>
        <input type="checkbox" name="repaet" id="repeat" value="repeat">
      </label>
    </div>
    <script>
      $('#repeat_on').hide();
      $('#repeat_off').show();
      
      if ($('#repeat:checked').val()) $('#slide-play-repeat > .fa-refresh').toggle();

      $('#slide-play-repeat > .fa-refresh').click(function(){ $('#slide-play-repeat > .fa-refresh').toggle(); });
    </script>
  </div><!-- /#heatmap_term_slide_ctrl -->
<% end %>


<script>
// ビーコン表示 >>
<%= render 'beacon_js' %>
// << ビーコン表示

// モバイル端末ボタン制御 >>
<%= render 'mobile_uuids_js' %>
// << モバイル端末ボタン制御

// ズームボタン制御 >>
<%= render 'zoom_js' %>
// << ズームボタン制御

var heatmapInstance = h337.create({
                          container: document.querySelector('#diagram-wrapper'),
                          radius: 20,
                          });

function clearDiagram() {
  heatmapInstance.setData({data:[]});
  $('#heatmap_term_slide_ctrl').hide();
};

function setResult(json) {
//  console.log('setResult start');
//  console.log('data count = ' + json.length);

  //heatmapInstance.addData(json);

  var data = {
      max: 10,
      min: 0,
      data: json,
  };
  heatmapInstance.setData(data);

//  console.log('setResult end');
};

var mobileLocations;
var getMobileLocations;
var stopFlag;

$('#loading-btn').click(function () {
  //$('#heatmap_term_slide_ctrl').hide();

  var mobileUuids = [];
  $('[name="mobile-uuid"]:checked').each(function(){
    mobileUuids.push($(this).val());
    });

//  if (mobileUuids.length == 0) {
//    alert('対象機器を選択してください');
//    return;
//  }

  var targetDate = $('#term-date').val();
  if (!targetDate) {
    alert('対象日付を選択してください');
    return;
  }

  var targetHour = $("#target-hour").val();
  if (!targetHour) {
    alert('対象時間を選択してください');
    return;
  }

  var btn = $(this)
  btn.button('loading');

  clearDiagram();

  $.ajax({
        url :"http://192.168.56.101:3000/api/mobile_locations/by_hour/",
        dataType : "jsonp",
        data : {
          //date : '2014-09-24',
          //hour : 17,
          date : targetDate,
          hour : targetHour
//          mobile_uuids : mobileUuids,
//          expand : diagramExpand,
        }
        }).done(function(data){
          if (data.length = 0) {
//          if (data[0]['mobile_uuid'] == null) {
            alert('該当データがありませんでした');
          }
          else {
            $('#heatmap_term_slide_ctrl').show();
            mobileLocations = parsePoints(targetDate, targetHour, data);
            alert('データ読込終了しました');
          }
        }).fail(function(data){
          console.log('error');
          //alert("error");
        }).always(function(data){
          btn.button('reset')
          //clearDiagram();
        });
});

function parsePoints(targetDate, targetHour, datas) {
  var points = [];
  for (var i = 0; i < 3600; i++) {
    points[i] = [];
  } 

  //var baseDate = Date.parse('2014-10-07T09:00:00.000+00:00');
  targetHour = ('00' + targetHour).slice(-2);
  var baseDate = Date.parse(targetDate + 'T' + targetHour + ':00:00.000+00:00');

  for (var i = 0; i < datas.length; i++) {
    var tmp1 = datas[i]['datas'];
    for (var key in tmp1) {
      var tmp2 = tmp1[key];
      for (var j = 0; j < tmp2.length; j++) {
        var point = tmp2[j];
        var tmpDate = Date.parse(point['mobile_t']); 
        var idx = (tmpDate - baseDate) / 1000;
        points[idx].push(point);
      }
    }
  }

  return points;
}

var slideCnt;
var slideStep = 1;
var slideMax = 60;
var dispDatas = [];
var dispMinites = 5;

var playSlider = $('#hide-slider').slider({
    max: slideMax,
    step: slideStep,
    tooltip: 'always',
    formatter: function(value) {
    return value + '分';
    }
}).on('slide', function(ev) {
  //$("#slider-val").text(ev.value);

  var idx = 0; 
  if(ev.value) {
    idx = ev.value
  }

  var end = idx * slideStep * 60;
  var start = end - dispMinites * 60;
  if (start < 0) start = 0; 
  
  var tmp = mobileLocations.slice(start, end);

  var tmp2 = [];
  for (var i = 0; i < tmp.length; i++) {
    var hoge = tmp[i];
    for (var j = 0; j < hoge.length; j++) {
      tmp2.push(hoge[j]);
    }
  }
  
  setResult(tmp2);
});

$('#slide-play').click(function() {
    if (!mobileLocations || mobileLocations.length === 0) {
      alert('表示できるデータがありません');
      return;
    }

    // playボタンを非活性
    $(this).hide();
    $('#slide-pause').show();

    // 各種ボタンも非活性
    guardButtons(true);

    stopFlag = false;

    var fuga = playSlider.slider('getValue');

    getMobileLocations = setInterval(function() {
      if (!stopFlag) {
        playSlider.slider('setValue', fuga * slideStep, true);
        fuga = fuga + 1;
      }

      //終了条件
      if (fuga > slideMax) {
        // リピート再生
        if ($('#repeat:checked').val()) {
          fuga = 0;
          playSlider.slider('setValue', 0, true);
        } 
        // 終了
        else {
          clearInterval(getMobileLocations);
          playSlider.slider('setValue', 0, true);
          $('#slide-pause').click(); 
        }
      }
      }, 750);
});
$('#slide-pause').click(function() {
    // ループ処理を停止
    stopFlag = true;
    clearInterval(getMobileLocations);

    // playボタンを活性

    //$('#slide-play').attr('disabled', false);
    //toggleMobileUuidsCB(false);

    $(this).hide();
    $('#slide-play').show();

    // 各種ボタン非活性
    guardButtons(false);
});
/*
$('#slide-stop').click(function() {
    // ループ処理を停止
    stopFlag = true;
    clearInterval(getMobileLocations);

    // heatmapを初期化
    clearDiagram();
    // playボタンを活性
    $('#slide-play').attr('disabled', false);
    //toggleMobileUuidsCB(false);
    // sliderを初期化
    playSlider.slider('setValue', 0, true);
});
 */

// playボタンを活性
$('#slide-play').show();
$('#slide-pause').hide();
$('#heatmap_term_slide_ctrl').hide();

$('#term-date').datepicker({
    format: 'yyyy-mm-dd',
    language: 'ja',
    todayHighlight: true,
})

</script>

app/views/booths/_form.html.erb
<%= form_for(@booth) do |f| %>
  <% if @booth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booth.errors.count, "error") %> prohibited this booth from being saved:</h2>

      <ul>
      <% @booth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :no %><br>
    <%= f.text_field :no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/booths/edit.html.erb
<h1>Editing booth</h1>

<%= render 'form' %>

<%= link_to 'Show', @booth %> |
<%= link_to 'Back', booths_path %>

app/views/booths/index.html.erb
<h1>Listing booths</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>No</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @booths.each do |booth| %>
      <tr>
        <td><%= booth.title %></td>
        <td><%= booth.no %></td>
        <td><%= link_to 'Show', booth %></td>
        <td><%= link_to 'Edit', edit_booth_path(booth) %></td>
        <td><%= link_to 'Destroy', booth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booth', new_booth_path %>

app/views/booths/new.html.erb
<h1>New booth</h1>

<%= render 'form' %>

<%= link_to 'Back', booths_path %>

app/views/booths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @booth.title %>
</p>

<p>
  <strong>No:</strong>
  <%= @booth.no %>
</p>

<%= link_to 'Edit', edit_booth_path(@booth) %> |
<%= link_to 'Back', booths_path %>